services:
  baileys-db:
    image: postgres
    container_name: baileys-db
    environment:
      POSTGRES_PASSWORD: 2024pass
      POSTGRES_DB: bailey
    ports:
      - "5432:5432"  # Exportado apenas para demonstração, remova em produção
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - wpp-net

  baileys-migration-init:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name:  baileys-migration-init
    environment:
      DATABASE_URL: postgres://postgres:2024pass@baileys-db:5432/bailey
    command: |
      sh -c 'npx prisma migrate deploy'
    depends_on:
      - baileys-db
    networks: 
      - wpp-net

  baileys-api:
    container_name: baileys-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: 'postgres://postgres:2024pass@baileys-db:5432/bailey'
      URL_WEBHOOK: 'https://REDACTED/api/REDACTED/MensagemRecebidaWebhook'
    depends_on:
      - baileys-db
      - baileys-migration-init
    networks: 
      - wpp-net

networks:
  wpp-net:
    driver: bridge
